# Generated by Django 5.1.3 on 2024-12-05 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
